<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cyz_address"
 *
 * Auto generated by Extension Builder 2017-09-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'tt_address fluid',
    'description' => 'Fluid-Template for tt_address',
    'category' => 'plugin',
    'author' => 'Luca Kredel',
    'author_email' => 'luca.kredel@cyperfection.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.8',
            'fluid' => '7.6.22-',
            'tt_address' => '3.2.2-',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
